server:
  port: 8082

spring:
  application:
    name: ORDER-SERVICE
  config:
    import: "optional:configserver:http://localhost:9296"  # ✅ added optional: prefix
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/orderdb
    username: root
    password: Root@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: "*"